export { default as Navbar } from './navbar/Navbar'
export { default as Footer } from './footer/Footer'
export { default as Contact } from './contact/Contact'
export { default as About } from './about/About'
export { default as Ipoteka } from './ipoteka/Ipoteka'
